### ISSUE TITLE
plotAssay

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/miaViz#114]
Not urgent.

If we currently want to visualize abundance of certain taxa in certain groups for example (e.g. box plot - x axis: group - y axis: taxa), we have to first

1. melt assay
2. ggplot

We could have plotAssay function that streamlines this.

**Comment by TuomasBorman** [comment]
See example of plotExpression. It seems to work as wanted

```
library(scater)
library(miaViz)

data("enterotype")
tse <- enterotype

# Choose certain features to plot
certain_features <- rownames(tse)[c(100, 200, 102)]

plotExpression(
    tse, certain_features,
    exprs_values = "counts",
    x = "ClinicalStatus", colour_by = "ClinicalStatus")
```

**Comment by antagomir** [comment]
Cool.

Note that scater pkg also switched to using `assay.type` instead of `exprs_values` after our suggestion (https://github.com/microbiome/mia/pull/341). So use that in plotExpression.

**Comment by TuomasBorman** [comment]
Reconsider this. There is need for boxplots.

**Comment by TuomasBorman** [comment]
This is a quick fix. If we cannot modify scater, we could easily just call plotExpression() and then modify the plot based on desired layout.

```
library(miaViz)
library(ggplot2)

data("GlobalPatterns")
tse <- GlobalPatterns

tse <- agglomerateByRank(tse, rank = "Phylum")
tse <- transformAssay(tse, method = "clr", pseudocount = 1)

# Create a violin plot
p <- plotExpression(tse, assay.type = "clr", features = rownames(tse)[1:5])
# Add boxplot layer
p <- p + geom_boxplot(outlier.shape = NA)
# Replace violin layer with boxplot layer
p$layers[1] <- p$layers[length(p$layers)]
p$layers[length(p$layers)] <- NULL
p
```

**Comment by antagomir** [comment]
Related to #104

**Comment by TuomasBorman** [comment]
Issue in scater https://github.com/alanocallaghan/scater/issues/207

**Comment by TuomasBorman** [comment]
The PR was merged.
