### ISSUE TITLE
New function: plot_spread ?

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaViz#13]
I suggest to add a new function that visualizes distribution of abundances per taxonomic group as a dotplot. We have used this in some publications and found it useful. Usefulness depends on the number of taxa, samples etc, as for any visualization.

Similar functionality has been implemented [in microbiome](https://github.com/microbiome/microbiome/blob/master/R/spreadplot.R) and works as follows:

```
library(microbiome)
data(dietswap)
spreadplot(transform(dietswap, "compositional"))
```

**Comment by FelixErnst** [comment]
This might be already available via `scater`

```r
library(scater)
se <- microbiomeDataSets::dietswap()
altExps(se) <- splitByRanks(se)
plotHighestExprs(altExp(se,"Genus"))
```

![image](https://user-images.githubusercontent.com/17824332/115203059-56e2c300-a0f7-11eb-811d-ddb50a04e0ce.png)

Maybe a wrapper with a more microbiome specific name might be warranted, aka. `plotHighestAbundance`

**Comment by microsud** [comment]
I was also thinking of the same function from scater and I have used it before for QC. IMO we need not add anything on top of it and just show this using scater in OMA?

**Comment by antagomir** [comment]
This is a good plan. Although I have to admit that I like the dotplot a bit more compared to this one with vertical lines.
