### ISSUE TITLE
Switch to mia data (remove microbiomeDataSets data)

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaViz#141]
Certain data sets were removed in microbiomeDataSets and miaViz builds are broken
https://bioconductor.org/checkResults/3.19/bioc-LATEST/miaViz/nebbiolo1-checksrc.html

Switch to using similarly named demo data sets from mia pkg.

**Comment by ake123** [comment]
I do not see any data called from  `microbiomeDataSets`. Does it include `SilvermanAGutData`?

**Comment by antagomir** [comment]
Perhaps you can remove "microbiomeDataSets" from DESCRIPTION and try to build & check the package, examples, tests and vignettes with 

devtools::document()
devtools::build()
devtools::check()
devtools::test()
devtools::run_examples()
devtools::run_vignettes()

etc

**Comment by antagomir** [comment]
Related to 
#122
#107
#90

**Comment by antagomir** [comment]
@ake123 is this something we can close now?

**Comment by antagomir** [comment]
> @ake123 is this something we can close now?

up
