### ISSUE TITLE
plotRDA improvements

### ISSUE THREAD

**Issue by TuomasBorman** [microbiome/miaViz#161]
On gitter channel, Adrián H.:

> Hi everyone, I have a question regarding plotRDA function. By default, it shows all the names of the variables used in the formula of runRDA. Can I tell the function to just plot some specific names? Using the same code as in the OMA book, at the RDA plot it shows the labels for variables ClinicalStatus + Gender + Age and their levels. How can I just display the ClinicalStatus rda info without displaying the info for Gender and Age? I am performing an analysis with too many covariates and the image generated by plotRDA has too much useless information. Thanks!!

-->

Check if this is already possible. At least it should already possible to modify those plotted labels. However, I believe that if you want to plot vectors, you have to plot them all.

**Comment by TuomasBorman** [comment]
Something like this

```
library(miaViz)
data("enterotype", package = "mia")
tse <- enterotype

# Run RDA and store results into TreeSE
tse <- addRDA(
    tse,
    formula = assay ~ ClinicalStatus + Gender + Age,
    FUN = getDissimilarity,
    distance = "bray",
    na.action = na.exclude
    )
plotRDA(tse, "RDA", vec.lab = c("-", "something", "-", "-", "-", "-"), add.significance = FALSE)
```
![image](https://github.com/user-attachments/assets/c3dcc3f5-6163-492a-a418-8749abd4b8be)

**Comment by adriherca** [comment]
Hi, here's an example using my dataset. I need to use many covariates and showing all the information, while correct, it's not optimal for publication. Also, I think that would be helpful to have an option to highlight the significant features or change the text color or something.
![imagen](https://github.com/user-attachments/assets/ee66712c-48fb-4006-81dd-9e164d882496)

**Comment by TuomasBorman** [comment]
Thank you for clarification! This is clearly something that we can improve. These are very good suggestions, but incorporating these to the method (or to examples) requires some work so this might take some time. We will keep you updated!

-Tuomas

**Comment by TuomasBorman** [comment]
Hi @adriherca!

The latest development version (install directly from `github devtools::install_github("microbiome/miaViz")` ) includes this option. Now you can control which vectors are showed. This is done by `add.vectors`. If you give character value instead of boolean, it will match that value to vectors. It is done with regular expression. See the examples below.

```
data("enterotype", package = "mia")
tse <- enterotype
#
tse <- addRDA(
    tse,
    formula = assay ~ ClinicalStatus + Gender + Age,
    FUN = getDissimilarity,
    distance = "bray",
    na.action = na.exclude
    )
#
# Select clinical status covariate, i.e., all vectors belonging to this group are showed
plotRDA(tse, "RDA", add.vectors = "ClinicalStatus")
# Select only UC group from clinical status to show. 
plotRDA(tse, "RDA", add.vectors = "clini.*uc", ignore.case = TRUE)
```
Love to hear your feedback!
