### ISSUE TITLE
Composition barplot

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaViz#20]
A typical way to visualize microbiome composition is the "Composition barplot" as shown e.g. in [microbiome tutorial](https://microbiome.github.io/tutorials/Composition.html) (see section with that name). 

Consider implementing this as a function, or as an option in an existing function that visualizes the composition (if not readily available).

Add example in miaViz vignette and/or OMA.

**Comment by antagomir** [comment]
This should be possible with 


```
library(mia)
library(miaViz)
data(GlobalPatterns)
tse <- GlobalPatterns
plotAbundance(tse, abund_values="counts", rank = "Phylum", order_sample_by = "Bacteroidetes")
```

However, when selecting `order_sample_by = "Bacteroidetes"` the figure does not seem to be sorted by Bacteroidetes abundance. 

Check why, and fix if necessary or add an option to sort based on the abundance of a given taxonomic group at the chosen level (as in the visualization example in microbiome tutorial linked above).

PR the changes to miaViz (if needed) and then add an example to OMA, section on [community composition](https://microbiome.github.io/OMA/microbiome-community.html#community-composition).

I suggest that @ChouaibB works on this, supervised by @tvborm . Then me and @FelixErnst will support where necessary.

**Comment by ChouaibB** [comment]
How about:
"plotAbundance(tse, abund_values="counts", rank = "Phylum", order_rank_by="revabund", order_sample_by = "Bacteroidetes")"
It gives the following:
![image](https://user-images.githubusercontent.com/86964562/126292908-144944ab-b1ff-4cee-8057-e6f2e521df5d.png)

**Comment by antagomir** [comment]
Ah, right. Of course, this does not work that well with the count assay. 

I suggest the following:

1) The figure was confusing with the count assay because I overlooked the fact that the data is visualized as relative abundances anyway. A warning might be in place if one tries to run this with something else than "relabundance" assay but the visualization is done with relabundance anyway? Then it looks like sample sorting is not correct, although it is.

2) Before the visualization, add a line that aggregates the rare taxa to "Other" category; an example is already shown in OMA section on [Visualizing the most dominant genus on PCoA](https://microbiome.github.io/OMA/microbiome-diversity.html#beta-diversity)

3) Can we add this example with relabundance to OMA, sorting by Bacteroidetes and showing the top-5 taxa + "Other"

**Comment by ChouaibB** [comment]
Just one more comment about sorting by samples. I might be a bit confused still, because I tried the following and it seems it does sort the samples:
```{r}
library(mia)
library(miaViz)
data(GlobalPatterns)
tse <- GlobalPatterns
plotAbundance(tse, rank="Phylum", add_legend=FALSE, add_x_text=TRUE) +
  theme(axis.text.x.bottom = element_text(angle = 90, hjust = 0))
plotAbundance(tse, rank="Phylum",order_sample_by = "Bacteroidetes", add_legend=FALSE,add_x_text=TRUE) +
  theme(axis.text.x.bottom = element_text(angle = 90, hjust = 0))
```
Output: (first without order_by_sample and second is)
![image](https://user-images.githubusercontent.com/86964562/126314674-fc7834e0-7831-4fbd-8038-703823c46df2.png)
![image](https://user-images.githubusercontent.com/86964562/126314719-b6e4c4d7-edb6-4328-b5dc-bf7612a0da82.png)

**Comment by antagomir** [comment]
Yes it does the sorting but if you sort by Bacteroidetes then you could expect to see that in the plot. The explanation is clear in this case but a warning might help uncautious users like me. 

I suggest to use minimal examples and exclude themselves and other elements in the code that are unrelated to the issue.

**Comment by antagomir** [comment]
The assay should be explicitly defined to avoid confusion?

**Comment by ChouaibB** [comment]
Guess for readability the line:
```{r}
tse <- relAbundanceCounts(tse)
```
Could be added.
In documentation the default values set for the args is clear about using relabundance, and gets calculated if not present.
I tested it when  "abund_values" not passed (like the earlier comment) by default it counts relative abundance if it is not present among the assays.

**Comment by antagomir** [comment]
Yes, it counts relabundances for the visualization.

But sorting is not done on that assay by default, i.e.

`plotAbundance(tse, rank="Phylum",order_sample_by = "Bacteroidetes")`

Does sorting for Bacteroidetes but does not specify which assay. 

`plotAbundance(tse, rank="Phylum",order_sample_by = "Bacteroidetes", abund_values="counts")`

would be explicit about the assay that is being used in the sorting. 

However, when I do 

```
tse <- relAbundanceCounts(tse)
plotAbundance(tse, rank="Phylum",order_sample_by = "Bacteroidetes", abund_values = "relabundance")
```

The values do not seem to be sorted by Bacteroidetes relative abundance.

Adding  the `order_rank_by` option does the trick with `revabund`
 
plotAbundance(tse, rank="Phylum",order_sample_by = "Bacteroidetes", abund_values = "relabundance", order_rank_by="revabund")

But the documentation is not very clear on how the abund and revabund are expected to differ, or what order_rank_by="name" really means/does.

`plotAbundance(tse, rank="Phylum",order_sample_by = "Bacteroidetes", abund_values = "relabundance", order_rank_by="abund")`

Action point: clarify function documentation and examples, and afterwards also add example in OMA.

**Comment by ChouaibB** [comment]
Ok I see your point clearly now.
I try figure out what "name" or "abund" do, then move to OMA.

**Comment by antagomir** [comment]
Also improvisaatio function documentation, I couldnt figure out from that. Ask support from the authors of this function if necessary

**Comment by ChouaibB** [comment]
Ok "name" sorts names/labels present in rank, if no rank is mentioned the first in taxonomyRanks (e.g. Kingdom) names are sorted. I double check with authors about all.
