### ISSUE TITLE
Fix GHA config

### ISSUE THREAD

**Issue by FelixErnst** [microbiome/miaViz#26]
Lets kick out Windows and macOS from the GitHub Action for now. @TuomasBorman: Are you interested?

See config in `mia` for example.

**Comment by antagomir** [comment]
Ok with me, although this brings an additional safety layer to the testing ecosystem..

**Comment by FelixErnst** [comment]
Sure, but Bioconductor will cover that in the end, won't it? For development, Linux only should be fine.

**Comment by antagomir** [comment]
Yes, True.

**Comment by TuomasBorman** [comment]
Ok, I can do that
