### ISSUE TITLE
Color selection in plotAbundanceDensity()

### ISSUE THREAD

**Issue by asierFernandezP** [microbiome/miaViz#35]
I am trying to obtain a Abundance Density plot using the ```plotAbundanceDensity()``` function. I want to colour the points according to a variable that is a column from ```colData```. There is no problem when doing this with the ```colour_by``` function, but I cannot select which specific colors I want for each of the groups. I have seen that there is an additional argument ```point_colour``` but this seems to work only when ```colour_by``` function is not used. Is there a way to select the colors of each the groups in the Abundance Density plot?. I am specifically pointing to the ```plotAbundanceDensity()``` function but this can be extended to any other function that allows to use the argument ```colour_by```.

Thanks in advance,

Asier

**Comment by antagomir** [comment]
I think we should avoid supporting standard ggplot manipulation operations that can be added afterwards. That would easily add a lot of complexity without little added value.

**Comment by asierFernandezP** [comment]
Thank you for your answers! Yes, you're right, this can be easily done with ggplot. And thanks for the great package, really useful!

**Comment by antagomir** [comment]
Very good to get feedback, this is early days still!
