### ISSUE TITLE
Add sample names to Abundance Plot

### ISSUE THREAD

**Issue by asierFernandezP** [microbiome/miaViz#36]
HI! I would like to ask if it is possible to add sample names or sample group names to Abundance Plots generated by ```PlotAbundance()``` function.  I am using ```order_sample_by```  option to order the samples, but I do not see any option to indicate the sample names o sample group names in the x axis of the plot. Must this be done also using ```ggplot``` options?

Thanks in advance,

Asier

**Comment by asierFernandezP** [comment]
Thank you! But is it also possible to display the group names (of the grouping variable that it is used in ```order_sample_by```) instead of the individual sample names? Otherwise it is difficult to fit all the individual names in the plot.

**Comment by antagomir** [comment]
Do you something like 

`plotAbundance(se, features = "SampleType")`

**Comment by asierFernandezP** [comment]
Yes, but this does indeed generate another barplot for the groups, right? And I could then merge both together using ```wrap_plots```. But I was trying to add only the group names (once for all the samples belonging to the same group) to the X axis of the abundance plots (as samples have already been ordered by groups) or add something that indicates the different groups of the samples without the need of adding this additional plot generated by ``features = "SampleType")```.

**Comment by antagomir** [comment]
Right. I am not sure if this is easily possible currently. It is rather complicated scenario to have in a general case, where the group sizes and numbers of groups can potentially vary a lot. Also not sure how good ggplot support there is to this feature. Ideally, this could utilize already existing ggplot techniques. If there are pointers, we could have a look.

**Comment by asierFernandezP** [comment]
Yes, thank you very much! I guess this is a rather specific case.

**Comment by FelixErnst** [comment]
Can you provide a workable example descibing your case?

I think the easiest solution would be to create a temporary object and rename the colnames. SOmething like this;

```r
tmp <- se
colnames(tmp) <- colData(tmp)$whatever
plotAbundance(se, add_x_text=TRUE)
```

Depending on your number of samples, this might look ok, but I would try to optimize the wrapping of the two objects. The example give in https://microbiome.github.io/miaViz/reference/plotAbundance.html

Can be tweaked using the patchwork functions. For example you can remove labels from the second object and print it 1/10th of hight of the first object. FOr more details have a look here https://patchwork.data-imaginist.com/

**Comment by FelixErnst** [comment]
Should the issue be closed?
