### ISSUE TITLE
sparseMatrix breaks plotAbundance(Density)

### ISSUE THREAD

**Issue by and3k** [microbiome/miaViz#37]
Hi :)

SummarizedExperiment objects are allowed to contain sparseMatrix objects instead of base matrix objects, but this breaks plotAbundance and plotAbundanceDensity:

```
library(Matrix)
library(miaViz)

data(GlobalPatterns, package = "mia")
plotAbundanceDensity(GlobalPatterns) # works
plotAbundance(GlobalPatterns) # works

assay(GlobalPatterns) <- as(assay(GlobalPatterns), "sparseMatrix")
plotAbundanceDensity(GlobalPatterns)
# Error in t.default(mat) : argument is not a matrix
plotAbundance(GlobalPatterns)
# Error in as.data.frame.default(.) : 
#   cannot coerce class ‘structure("dgCMatrix", package = "Matrix")’ to a data.frame
```

Similar to https://github.com/microbiome/mia/issues/151

Thank you!

Best,
Bela

**Comment by antagomir** [comment]
Ah, perfect - we will need to check asap, thanks!

**Comment by TuomasBorman** [comment]
Hi! 

Thanks for noticing this and thanks for nice example. This can be fixed by converting `sparseMatrix` into `matrix`. 

-Tuomas

**Comment by antagomir** [comment]
Close the issue when solved.

**Comment by TuomasBorman** [comment]
If the PR is ok, then it can be merged and this issue can be closed

**Comment by antagomir** [comment]
Ah yes. Somehow I had missed the review. FE will make the final judgment.

**Comment by antagomir** [comment]
Oh, this is miaViz. I think we can accept the PR already.
