### ISSUE TITLE
print x-axis label in plotAbundance

### ISSUE THREAD

**Issue by kusandeep** [microbiome/miaViz#55]
Hi, 
This might be a very basic question. How can I print x-axis label in `plotAbundance`? 

`P_g <-  plotAbundance(tse, abund_values="relabundance", rank = "Genus", ncol = 1, layout = "bar",
              order_rank_by="abund")`

**Comment by antagomir** [comment]
These are ggplot objects. I think it should work with `+ labs(x = "My X axis title")`

**Comment by TuomasBorman** [comment]
Hi, 

or if you mean the names of samples, you can add them with `add_x_text = TRUE` 

https://microbiome.github.io/miaViz/reference/plotAbundance.html (6th example)
