### ISSUE TITLE
Ordination plots with trajectories: add examples

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaViz#64]
Ordination plots can be complemented with trajectories over points when time series are available for some or all subjects, other entities. It is not yet clear whether this would deserve its own function but illustrative examples for basic use cases can be useful.

Examples to implement:

1) Paired data with multiple time points: 
- plot data with some ordination method (PCA, MDS, or other)
- overlay trajectory for (a) all and (b) one or more selected subjects (based on subject ID/s, based on top10% changes, based on group indicated in colData)
- indicate the strength of change by color
- should be shown for a general case where the subjects may have differing number of time points, including singletons (all samples shown on ordination for a default example)

2) Paired data with two time points. This is already included in (1) but is a simpler case and could potentially come with some extra capabilities that are feasible for general time series.

The most suitable open data set for this could be discussed.

**Comment by antagomir** [comment]
This would be the file: [vignettes/miaViz.Rmd](https://github.com/microbiome/miaViz/blob/master/vignettes/miaViz.Rmd)

**Comment by antagomir** [comment]
Could be done with the vaginal microbiota data set from [Gajer et al. (2012)](https://doi.org/10.1126/scitranslmed.3003605) also to reproduce the figure I created for the review [Faust et al. (2015)](https://ars.els-cdn.com/content/image/1-s2.0-S1369527415000478-gr4.jpg)

**Comment by ChouaibB** [comment]
Where can I get the phyloseq object?
