### ISSUE TITLE
Default ranks

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaViz#88]
In `plotAbundance()` the default rank is set to `rank = taxonomyRanks(x)[1]`. 

This can be confusing since the data is aggregated to higher than original level without user intervention.

Perhaps better to have no rank specified by default (using the highest resolution data available): `rank=NULL`?

**Comment by himmil** [comment]
If the default for rank is set to NULL, then plotAbundance() has an identical default function to plotExpression() from scater. Is it a problem?

**Comment by antagomir** [comment]
@himmil could you check this with Noah for a practice.
