### ISSUE TITLE
Strange example

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaViz#96]
The first example on the [plotAbundance](https://microbiome.github.io/miaViz/reference/plotAbundance.html) reference page asks to plot "counts" assay but the figure is relative abundances. This makes the example confusing.

Explain the default behavior, if the relabundance plotting is automated as a default; or (even better?) update the figure so that it plots by default what is asked (here, counts)

**Comment by SHillman836** [comment]
https://github.com/microbiome/miaViz/pull/126 - for the change

**Comment by antagomir** [comment]
@SHillman836 ok so this issue can be closed?

**Comment by SHillman836** [comment]
yes

**Comment by antagomir** [comment]
Great. I will close this now. Do actively close issues that are done.
